name: rsue_app
description: rsue_app
version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=2.19.0-214.0.dev <3.0.0"
dependencies:
  shared_preferences: ^2.0.15
  hive_flutter: ^1.1.0
  url_launcher: ^6.1.5
  hive: ^2.2.3
  intl: ^0.17.0
  rounded_loading_button: ^2.1.0
  fluentui_system_icons: ^1.1.178
  flutter_zoom_drawer: ^3.0.3
  flutter:
    sdk: flutter
  provider: ^6.0.3
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  html: ^0.15.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.1.1
  week_of_year: ^2.0.0
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.18.3
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik_glitch
      fonts: 
        - asset: assets/fonts/rubik_glitch/rubikglitch-regular.ttf
          weight: 500
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 100
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
  assets:
    - assets/icons/faculty/ktiib/
    - assets/icons/faculty/mip/
    - assets/icons/faculty/eif/
    - assets/icons/faculty/fliz/
    - assets/icons/faculty/td/
    - assets/icons/faculty/u/
    - assets/icons/faculty/uef/
    - assets/images/

